[mongodb]
mongodb-dev.rakeshdev.online 

[catalogue]
catalogue-dev.rakeshdev.online

[redis]
redis-dev.rakeshdev.online

[user]
user-dev.rakeshdev.online


[cart]
cart-dev.rakeshdev.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.rakeshdev.online
CATALOGUE_HOST=catalogue-dev.rakeshdev.online 
REDIS_HOST=redis-dev.rakeshdev.online
USER_HOST=user-dev.rakeshdev.online




