[mongodb]
mongodb-dev.rakeshdev.online 

[catalogue]
catalogue-dev.rakeshdev.online

[redis]
redis-dev.rakeshdev.online

[user]
user-dev.rakeshdev.online

[user]
3.229.122.150



[cart]
cart-dev.rakeshdev.online

[mysql]
mysql-dev.rakeshdev.online

[shipping]
shipping-dev.rakeshdev.online

[rabbitmq]
rabbitmq-dev.rakeshdev.online

[payment]
payment-dev.rakeshdev.online

[frontend]
frontend-dev ansible_host=3.84.185.241 ansible_user=ec2-user


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.rakeshdev.online
CATALOGUE_HOST=catalogue-dev.rakeshdev.online 
REDIS_HOST=redis-dev.rakeshdev.online
USER_HOST=user-dev.rakeshdev.online
CART_HOST=cart-dev.rakeshdev.online
MYSQL_HOST=mysql-dev.rakeshdev.online
SHIPPING_HOST=shipping-dev.rakeshdev.online
RABBITMQ_HOST=rabbitmq-dev.rakeshdev.online
PAYMENT_HOST=payment-dev.rakeshdev.online
FRONTEND_HOST=frontend-dev.rakeshdev.online




