- name: Configure Shipping Server
  hosts: shipping
  become: yes

  vars:
    app_dir: /app

  tasks:

  - name: Install Maven, MySQL client, Java
    ansible.builtin.dnf:
      name:
        - maven
        - mysql
        - java-17-openjdk
      state: present

  - name: Create roboshop system user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: "{{ app_dir }}"
      shell: /sbin/nologin

  - name: Remove old app directory
    ansible.builtin.file:
      path: "{{ app_dir }}"
      state: absent

  - name: Create app directory
    ansible.builtin.file:
      path: "{{ app_dir }}"
      state: directory
      owner: roboshop
      group: roboshop

  - name: Remove old shipping zip
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: Download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Unarchive shipping
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: "{{ app_dir }}"
      remote_src: yes

  - name: Build application using Maven
    ansible.builtin.command: mvn clean package
    args:
      chdir: "{{ app_dir }}"

  - name: Rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: "{{ app_dir }}"

  - name: Copy shipping systemd service
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Install Python dependencies for MySQL
    ansible.builtin.pip:
      name:
        - cryptography
        - PyMySQL
      executable: pip3

  - name: Import Shipping Schema
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
      - "{{ app_dir }}/db/schema.sql"
      - "{{ app_dir }}/db/app-user.sql"
      - "{{ app_dir }}/db/master-data.sql"

  - name: Start and Enable Shipping Service
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
